### ISSUE TITLE
es.test.mode "info" is sending results that doesn't contain errors

### ISSUE THREAD

**Issue by hanaleung** [delirius325/jmeter-elasticsearch-backend-listener#22] opened 2018-05-31 19:05 UTC
I'm testing on jmeter 4.0 and setting es.test.mode="info" is still sending messages to ElasticSearch even when there isn't an error.

I'm using ElasticSearch 6.2.4

![image](https://user-images.githubusercontent.com/39808956/40802465-aa05f3ac-64e3-11e8-89a3-272aa683c852.png)

Kibana Result without filter:
![image](https://user-images.githubusercontent.com/39808956/40802572-f60d3526-64e3-11e8-8fda-b887de3aa874.png)

Filtering my messages based on ErrorCount:1:

![image](https://user-images.githubusercontent.com/39808956/40802602-09ee03a4-64e4-11e8-8914-51fd4cb6a24e.png)

**Comment by delirius325** [comment] 2018-05-31 19:07
Hey @hanaleung ,

I'll be glad to look into the issue. May I know which realease of the plugin you are currently using?

Thanks,

**Comment by hanaleung** [comment] 2018-05-31 19:12
Version 2.2.5

**Comment by delirius325** [comment] 2018-05-31 19:49
Using version 2.2.5 myself,

I am unable to reproduce the issue on a single JMeter execution. I'll have to try on a remote execution later tonight.

<img width="1676" alt="screen shot 2018-05-31 at 3 46 45 pm" src="https://user-images.githubusercontent.com/6709533/40804719-27ca5296-64ea-11e8-9229-9d3fb20ff5a2.png">
<img width="1220" alt="screen shot 2018-05-31 at 3 47 23 pm" src="https://user-images.githubusercontent.com/6709533/40804720-27e0ccc4-64ea-11e8-9a2c-fe49c1fee7cb.png">
<img width="1236" alt="screen shot 2018-05-31 at 3 47 32 pm" src="https://user-images.githubusercontent.com/6709533/40804721-27ed0ffc-64ea-11e8-8340-47ffd5f9a35e.png">

**Comment by delirius325** [comment] 2018-05-31 19:55
Would it be possible for you to supply me with the JSON data of the samplers for which the request/response body should not appear? (don't forget to blur the information related to the app you are testing)

Thanks,

**Comment by delirius325** [comment] 2018-05-31 20:03
As defined in the documentation though:

> Info mode should be used when the tests are being executed in a production context. This mode will only send the details of the responses upon failed requests. This allows you to be able to locate the errors when visualizing the tests through either Kibana/Grafana.

By "details" what we mean is that only the samplers which are unsuccessful will have their request/response body sent to ElasticSearch. It doesn't mean that only the errors will be sent to ElasticSearch.

It could however, be a good idea to introduce such a mode.

Thanks,

**Comment by hanaleung** [comment] 2018-05-31 20:13
Hi, 

i may be misinterpretting what is a failed request, but here is what i expect should be sent to ElasticSearch under "info" mode which i do see on elasticSearch and can identify via ErrorCount field.

`{
  "_index": "stockholm_capacity",
  "_type": "SampleResult",
  "_id": "a4bDt2MBDfEYHFPh-WVH",
  "_version": 1,
  "_score": null,
  "_source": {
    "EndTimeInMs": 1527796463910,
    "ContentType": "",
    "EndTime": "2018-05-31T15:54:23.910-0400",
    "IdleTime": 0,
    "ElapsedTime": "Jan 31, 2018 12:36:53 AM",
    "ErrorCount": 1,
    "Timestamp": "2018-05-31T15:54:23.910-0400",
    "URL": "_removed_",
    "Bytes": 1158,
    "SentBytes": 0,
    "ElapsedTimeInMs": -556,
    "AllThreads": 118,
    "DataType": "text",
    "ResponseTime": 0,
    "SampleCount": 1,
    "ConnectTime": 0,
    "RequestHeaders": "",
    "RequestBody": "_removed_",
    "StartTimeInMs": 1527796463910,
    "ResponseCode": "Non HTTP response code: java.net.URISyntaxException",
    "StartTime": "2018-05-31T15:54:23.910-0400",
    "ResponseMessage": "Non HTTP response message: Illegal character in path at index 104: _removed_",
    "ResponseHeaders": "",
    "AssertionResults": [
      {
        "failure": true,
        "name": "json_assertion",
        "failureMessage": "Expected to find an object with property ['catalogGroupView'] in path $ but found 'java.lang.String'. This is not a json object according to the JsonProvider: 'com.jayway.jsonpath.spi.json.JsonSmartJsonProvider'."
      }
    ],
    "Latency": 0,
    "ResponseBody": "",
    "GrpThreads": 118,
    "BuildNumber": 0,
    "BodySize": 0,
    "ThreadName": "guest_shopper_api 1-5",
    "SampleLabel": "_removed_"
  },
  "fields": {
    "EndTime": [
      "2018-05-31T19:54:23.910Z"
    ],
    "StartTime": [
      "2018-05-31T19:54:23.910Z"
    ],
    "Timestamp": [
      "2018-05-31T19:54:23.910Z"
    ]
  },
  "sort": [
    1527796463910
  ]
}`


And then here is what I don't expect to be logged but is currently being logged anyway:

`{
  "_index": "stockholm_capacity",
  "_type": "SampleResult",
  "_id": "X5DTt2MBDfEYHFPhYpk4",
  "_version": 1,
  "_score": null,
  "_source": {
    "EndTimeInMs": 1527797473836,
    "ContentType": "application/json",
    "EndTime": "2018-05-31T16:11:13.836-0400",
    "IdleTime": 0,
    "ElapsedTime": "Jan 31, 2018 12:53:43 AM",
    "ErrorCount": 0,
    "Timestamp": "2018-05-31T16:11:13.765-0400",
    "URL": "_removed_",
    "Bytes": 1025,
    "SentBytes": 293,
    "ElapsedTimeInMs": -489,
    "AllThreads": 150,
    "DataType": "text",
    "ResponseTime": 71,
    "SampleCount": 1,
    "ConnectTime": 0,
    "StartTimeInMs": 1527797473765,
    "ResponseCode": "200",
    "StartTime": "2018-05-31T16:11:13.765-0400",
    "AssertionResults": [
      {
        "failure": false,
        "name": "json_assertion",
        "failureMessage": ""
      }
    ],
    "Latency": 71,
    "GrpThreads": 150,
    "BuildNumber": 0,
    "BodySize": 727,
    "ThreadName": "guest_shopper_api 1-137",
    "SampleLabel": "_removed_"
  },
  "fields": {
    "EndTime": [
      "2018-05-31T20:11:13.836Z"
    ],
    "StartTime": [
      "2018-05-31T20:11:13.765Z"
    ],
    "Timestamp": [
      "2018-05-31T20:11:13.765Z"
    ]
  },
  "sort": [
    1527797473765
  ]
}`

**Comment by delirius325** [comment] 2018-06-01 13:13
Hey @hanaleung,

I released version 2.3.0 a few minutes ago : https://github.com/delirius325/jmeter-elasticsearch-backend-listener/releases/tag/2.3.0 

Feel free to manually upgrade and use the "error" test mode. The "error" test mode will only send the samplers that failed to the ElasticSearch engine :) !

_Waiting for the JAR file to be on Maven's central repository before pushing the new version to JMeter-Plugins_

Closing the issue :) 
Cheers,

**Closed by delirius325** 2018-06-01 13:13 UTC
Labels: enhancement

**Comment by hanaleung** [comment] 2018-06-01 13:18
Thanks for clearing up my misunderstanding and your prompt response.
it seems error mode is what i was looking for and i had thought info mode was that behavior but now i see the difference.
I'll pull the latest and I'll give the error mode a try

Cheers!

**Comment by delirius325** [comment] 2018-06-01 18:17
@hanaleung : You're very welcome, don't forget to star the repo so it gets noticed :) !

As a side note, PR created on Jmeter-plugins

https://github.com/undera/jmeter-plugins/pull/257
