### ISSUE TITLE
Sample errors not sent to backend

### ISSUE THREAD

**Issue by ncasaux** [delirius325/jmeter-elasticsearch-backend-listener#26] opened 2018-06-15 16:31 UTC
Hello!

It seems that when a sample fails, the sample results are never sent to ElasticSearch. I tried with the "info" mode and the "debug" mode.
I used some JMS Publisher samples for my tests. The successfull ones are inserted in ES, but not the others (when I used an incorrect connection for example).

**Comment by delirius325** [comment] 2018-06-15 17:58
Hi @ncasaux ,

I'll be looking at this tonight, most likely an error with the most recent release. Can you confirm by reverting to 2.2.5 manually? If not, I'll just test it out myself later.

Thanks a lot for noticing me about the issue!

**Comment by ncasaux** [comment] 2018-06-16 18:34
Hello,

Well, it seems more complex than expected...
Actually this issue is not related to your plug-in, I think it's a bug in JMeter which sends incorrect timestamp values when the JMS Publisher sample fails.
I raised an issue: https://bz.apache.org/bugzilla/show_bug.cgi?id=62464
I think you could reproduce it with this JMS Publisher, but the problem is not really your :)
You can close this issue if you want.

**Comment by pmouawad** [comment] 2018-06-17 19:52
Hello,
Issue has been fixed in jmeter and will be available in 4.1
Regards

**Comment by delirius325** [comment] 2018-06-18 18:59
Hi all,

Thanks for the follow up! Glad to know it's not a specific issue with the plugin and that the problem is fixed in jmeter 4.1.

Regards,

**Closed by delirius325** 2018-06-18 18:59 UTC
Labels: bug
