### ISSUE TITLE
How to send build number, if i am running jmeter in N-GUI mode  ?

### ISSUE THREAD

**Issue by tripaak** [delirius325/jmeter-elasticsearch-backend-listener#69] opened 2019-09-24 14:41 UTC
Hi Delirius,

I am exploring jmeter and using your backend listener to push my result to elastic and kibana.

I want to send build number as well with my result .

can you guide me how to achieve this ? I am running jmeter in Non GUI mode .

Thanks in advance .

**Comment by tripaak** [comment] 2019-09-24 17:32
additional issue , when i run test plan with back end listener enabled i get below error.

Uncaught Exception java.lang.IllegalStateException: Failed calling setupTest. See log file for details.

**Comment by sudgarre** [comment] 2019-10-03 12:31
@delirius325 : I am also facing the same issue. Can you please confirm if i am missing something ?

**Comment by tripaak** [comment] 2019-10-03 12:40
@sudgarre @delirius325 

I tried with GUI options
I am able to send build no with GUI using below command .

jmeter -t "testplan.jmx" -JBuildNumber XX

but the problem now is,  accepted build number is only number , if I put any text in it,  it is shows java error

**Comment by sudgarre** [comment] 2019-10-03 12:43
Thanks @tripaak but the build number for my case is set when a jenkins build is triggered
Looks to be a Duplicate of 50#

**Comment by delirius325** [comment] 2019-10-03 16:59
Hi guys,

It's tough to really understand what's going on, especially for the raised exception. Could it be possible, have a screenshot of your ES Backend Listener's configuration as well as the complete JMeter's log and the console log (they are two different things).

Thanks,

**Closed** 2020-02-20 14:49 UTC
Labels: bug
